2 commit
andrehsym/school_re pull request #1
Opened 2022-02-19 17:19 UTC by andrehsym

2022-02-22 19:18 UTC, rmuhamedgaliev approved these changes
Принято! Поправь небольшие стилистические замечания и мерж в мастер! 💪

2022-02-22 19:18 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school_re/service/impl/StudentServiceImpl.java
> +    @Override //PUT
Нет смысла писать эти комментарии. лучше удалить

2022-02-22 19:18 UTC, rmuhamedgaliev commented on src/main/resources/application.properties
> +#spring.jpa.hibernate.ddl  = update
Закомментированный код лучше сразу удалить

2022-02-22 19:18 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school_re/controller/FacultyController.java
> +    @PutMapping()
Пустые скобки можно удалить

2022-02-22 19:18 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school_re/controller/StudentController.java
> +        if (filterStudentsByAge.isEmpty()) {
а зачем использовать Set? Это дорогая для памяти коллекция, если хочешь уникальности, то в SQL  есть https://www.w3schools.com/sql/sql_distinct.asp

2022-02-23 16:19 UTC, andrehsym commented on src/main/java/ru/hogwarts/school_re/controller/StudentController.java
> +        if (filterStudentsByAge.isEmpty()) {
спасибо, полезный ресурс
я так понял, что то, что ты скинул - это пример запроса, который можно использовать непосредственно при работе с подключенной базой данных через идею в консоли. А можно как-нибудь для метода фильтрации студентов по возрасту использовать SQL-запрос? Я так понял, что возможно его можно прописывать в репозитории с использованием аннотации @Query над методом фильтрации... что-то вроде ("SELECT name FROM Student WHERE age=")... но как конкретно составить этот запрос, чтобы он использовал принимаемое значение age, не понимаю

2022-02-25 21:19 UTC, rmuhamedgaliev requested changes
Требуются правки

2022-02-26 19:30 UTC, rmuhamedgaliev approved these changes
Принято! ✅

2022-03-01 20:11 UTC, rmuhamedgaliev approved these changes
Принято! ✅

2022-03-06 17:54 UTC, merged